// Document formatter utility to format documents with headers and footers from print templates

// Default print template settings (fallback if not set in setup)
const defaultTemplate = {
  headerImage: null,
  footerContent: 'Smart Hospital System | Contact: +1-234-567-8900 | Email: info@smarthospital.com',
  footerFormat: {
    textStyle: 'normal',
    bold: false,
    italic: false,
    underline: false,
    small: true,
    alignment: 'center'
  }
};

// Simulated function to get print templates from system setup
// In a real application, this would fetch from the setup module or API
export const getPrintTemplate = (templateType = 'insurance-document') => {
  // This would normally fetch from the Setup module's state
  // For now, we'll return a mock template that can be configured
  const templates = {
    'insurance-document': {
      headerImage: null,
      footerContent: 'Smart Hospital System | 123 Medical Ave, Health City, HC 12345 | Phone: (555) 123-4567 | Email: insurance@smarthospital.com | License: MED-2025-001',
      footerFormat: {
        textStyle: 'normal',
        bold: false,
        italic: false,
        underline: false,
        small: true,
        alignment: 'center'
      }
    },
    'pharmacy': {
      headerImage: null,
      footerContent: 'Smart Pharmacy | 456 Wellness Blvd, Health City, HC 12346 | Phone: (555) 123-4568 | Email: pharmacy@smarthospital.com | License: PHARM-2025-001',
      footerFormat: {
        textStyle: 'normal',
        bold: false,
        italic: false,
        underline: false,
        small: true,
        alignment: 'center'
      }
    }
  };

  return templates[templateType] || defaultTemplate;
};

// Format document header
export const formatDocumentHeader = (templateType = 'insurance-document', customHeader = null) => {
  const template = getPrintTemplate(templateType);
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  const currentTime = new Date().toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit' 
  });

  let header = '';
  
  // Add header image placeholder if exists
  if (template.headerImage) {
    header += `[HEADER IMAGE: ${template.headerImage}]\n`;
  } else {
    // Default hospital header
    header += `═══════════════════════════════════════════════════════════════\n`;
    header += `                         SMART HOSPITAL SYSTEM                    \n`;
    header += `                      Comprehensive Healthcare Solutions          \n`;
    header += `                    123 Medical Avenue, Health City, HC 12345    \n`;
    header += `                Phone: (555) 123-4567 | Fax: (555) 123-4568     \n`;
    header += `                    Email: contact@smarthospital.com              \n`;
    header += `═══════════════════════════════════════════════════════════════\n`;
  }
  
  // Add document specific header
  if (customHeader) {
    header += `\n${customHeader}\n`;
  }
  
  // Add date and time
  header += `\nGenerated on: ${currentDate} at ${currentTime}\n`;
  header += `───────────────────────────────────────────────────────────────\n\n`;
  
  return header;
};

// Format document footer
export const formatDocumentFooter = (templateType = 'insurance-document') => {
  const template = getPrintTemplate(templateType);
  let footer = '\n\n───────────────────────────────────────────────────────────────\n';
  
  // Apply footer formatting
  let footerContent = template.footerContent || defaultTemplate.footerContent;
  
  if (template.footerFormat.bold) {
    footerContent = `**${footerContent}**`;
  }
  
  if (template.footerFormat.italic) {
    footerContent = `*${footerContent}*`;
  }
  
  if (template.footerFormat.underline) {
    footerContent = `_${footerContent}_`;
  }
  
  // Add alignment
  switch (template.footerFormat.alignment) {
    case 'center':
      const contentLength = footerContent.length;
      const padding = Math.max(0, (63 - contentLength) / 2);
      footer += ' '.repeat(Math.floor(padding)) + footerContent + '\n';
      break;
    case 'right':
      const rightPadding = Math.max(0, 63 - footerContent.length);
      footer += ' '.repeat(rightPadding) + footerContent + '\n';
      break;
    default: // left
      footer += footerContent + '\n';
  }
  
  // Add system info
  footer += '\nDocument generated by Smart Hospital System v2.0\n';
  footer += `Print Time: ${new Date().toLocaleString()}\n`;
  footer += '═══════════════════════════════════════════════════════════════';
  
  return footer;
};

// Main function to format complete document
export const formatDocument = (content, documentType, templateType = 'insurance-document', options = {}) => {
  const { 
    customHeader = null,
    patientInfo = null,
    hospitalInfo = null 
  } = options;

  // Create document-specific header
  let docHeader = '';
  switch (documentType) {
    case 'pre-auth':
      docHeader = `                    INSURANCE PRE-AUTHORIZATION REQUEST\n                              Document Type: Pre-Authorization`;
      break;
    case 'claim':
      docHeader = `                         INSURANCE CLAIM FORM\n                              Document Type: Insurance Claim`;
      break;
    case 'medical-report':
      docHeader = `                           MEDICAL REPORT\n                              Document Type: Medical Report`;
      break;
    default:
      docHeader = `                        INSURANCE DOCUMENT\n                              Document Type: ${documentType}`;
  }
  
  // Add patient info to header if provided
  if (patientInfo) {
    docHeader += `\n\nPatient Information:`;
    docHeader += `\nName: ${patientInfo.patientName || patientInfo.name || 'N/A'}`;
    docHeader += `\nID: ${patientInfo.id || 'N/A'}`;
    docHeader += `\nPolicy: ${patientInfo.policyNumber || 'N/A'}`;
  }

  const header = formatDocumentHeader(templateType, docHeader);
  const footer = formatDocumentFooter(templateType);
  
  return header + content + footer;
};

// HTML formatter for modal display
export const formatDocumentHTML = (content, documentType, templateType = 'insurance-document', options = {}) => {
  const { 
    patientInfo = null 
  } = options;

  const template = getPrintTemplate(templateType);
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  const currentTime = new Date().toLocaleTimeString('en-US', { 
    hour: '2-digit', 
    minute: '2-digit' 
  });

  // Create HTML header
  let htmlHeader = `
    <div style="text-align: center; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px;">
      <h1 style="color: #2563eb; font-size: 28px; margin: 0; font-weight: bold;">SMART HOSPITAL SYSTEM</h1>
      <p style="color: #64748b; font-size: 16px; margin: 5px 0;">Comprehensive Healthcare Solutions</p>
      <p style="color: #64748b; font-size: 14px; margin: 5px 0;">123 Medical Avenue, Health City, HC 12345</p>
      <p style="color: #64748b; font-size: 14px; margin: 5px 0;">Phone: (555) 123-4567 | Email: contact@smarthospital.com</p>
    </div>
  `;

  // Document type specific header
  let docTypeHeader = '';
  switch (documentType) {
    case 'pre-auth':
      docTypeHeader = `<h2 style="text-align: center; color: #dc2626; margin: 20px 0;">INSURANCE PRE-AUTHORIZATION REQUEST</h2>`;
      break;
    case 'claim':
      docTypeHeader = `<h2 style="text-align: center; color: #059669; margin: 20px 0;">INSURANCE CLAIM FORM</h2>`;
      break;
    case 'medical-report':
      docTypeHeader = `<h2 style="text-align: center; color: #7c3aed; margin: 20px 0;">MEDICAL REPORT</h2>`;
      break;
    default:
      docTypeHeader = `<h2 style="text-align: center; color: #2563eb; margin: 20px 0;">INSURANCE DOCUMENT</h2>`;
  }

  // Patient info section
  let patientSection = '';
  if (patientInfo) {
    patientSection = `
      <div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <h3 style="color: #1e293b; margin-top: 0;">Patient Information</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Name:</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${patientInfo.patientName || patientInfo.name || 'N/A'}</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Patient ID:</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${patientInfo.id || 'N/A'}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Policy Number:</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${patientInfo.policyNumber || 'N/A'}</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #475569;">Insurance Provider:</td>
            <td style="padding: 8px; border-bottom: 1px solid #e2e8f0; color: #1e293b;">${patientInfo.insuranceProvider || 'N/A'}</td>
          </tr>
        </table>
      </div>
    `;
  }

  // Format main content
  const formattedContent = content.replace(/\n/g, '<br>');

  // Create HTML footer
  let htmlFooter = `
    <div style="border-top: 2px solid #e2e8f0; padding-top: 20px; margin-top: 30px; text-align: center;">
      <p style="color: #64748b; font-size: 14px; margin: 5px 0;">${template.footerContent}</p>
      <p style="color: #9ca3af; font-size: 12px; margin: 10px 0;">Document generated on ${currentDate} at ${currentTime}</p>
      <p style="color: #9ca3af; font-size: 12px; margin: 5px 0;">Smart Hospital System v2.0</p>
    </div>
  `;

  return `
    <div style="max-width: 800px; margin: 0 auto; padding: 40px; font-family: Arial, sans-serif; line-height: 1.6;">
      ${htmlHeader}
      ${docTypeHeader}
      ${patientSection}
      <div style="margin: 30px 0;">
        ${formattedContent}
      </div>
      ${htmlFooter}
    </div>
  `;
};

export default {
  getPrintTemplate,
  formatDocumentHeader,
  formatDocumentFooter,
  formatDocument,
  formatDocumentHTML
};
